-- O bootstrap (config_sistema, grade preco_hora, mensagem_template) virou uma MIGRATION
-- idempotente (20260704120000_bootstrap.sql) para ir também à produção via `db push`.
-- Aqui não há nada dev-only: os dados de teste (crianças etc.) ficam em `npm run seed:dev`.
